# Generated by Django 6.0 on 2026-01-01 23:48

import core.models
import stdimage.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeaturedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Criação')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='Atualização')),
                ('active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('feature', models.CharField(max_length=100, verbose_name='Recurso')),
                ('description', models.TextField(max_length=200, verbose_name='Descrição')),
                ('icon', models.CharField(choices=[('lni-rocket', 'Foguete'), ('lni-laptop-phone', 'Laptop e Telefone'), ('lni-cup', 'Copo'), ('lni-leaf', 'Folha'), ('lni-layers', 'Camadas'), ('lni-briefcase', 'Mala')], max_length=20, verbose_name='Ícone')),
            ],
            options={
                'verbose_name': 'Item em Destaque',
                'verbose_name_plural': 'Itens em Destaque',
            },
        ),
        migrations.AlterField(
            model_name='employee',
            name='photo',
            field=stdimage.models.StdImageField(force_min_size=False, upload_to=core.models.upload_to_instance, variations={'thumb': {'crop': True, 'height': 480, 'width': 480}}, verbose_name='Foto'),
        ),
    ]
